# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'JustAnotherMeteoApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JustAnotherMeteoApp
  pod 'Alamofire'

  target 'JustAnotherMeteoAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JustAnotherMeteoAppUITests' do
    # Pods for testing
  end

end
